[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

# Handle static files first
[[redirects]]
  from = "/message/*.html"
  to = "/message/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/message/*/"
  to = "/message/:splat/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/message/*"
  to = "/message/:splat/index.html"
  status = 200
  force = true

# Handle API and data files
[[redirects]]
  from = "/messages.json"
  to = "/messages.json"
  status = 200
  force = true

[[redirects]]
  from = "/@data/*"
  to = "/@data/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# Handle sitemap and robots
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/news-sitemap.xml"
  to = "/news-sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

# Handle manifest
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = true

# Handle SPA routes last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: blob:; font-src 'self' https: data:;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache control for static files
[[headers]]
  for = "/message/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/news-sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@azure/identity", "@azure/data-tables"] 