name: update-message-center-data

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '@data/**'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:          
      - uses: actions/checkout@v3
      
      - name: Setup config
        run: |
          echo '{
            "tenantId": "${{ secrets.TENANT_ID }}",
            "clientId": "${{ secrets.CLIENT_ID }}"
          }' > ./@build/config-m365.json
        shell: pwsh
        
      - name: Get messages from Message Center
        run: |
          pwsh ./@build/Update-Site.ps1 -GraphSecret ${{ secrets.GRAPH_SECRET }}
        shell: pwsh
        
      - name: Update repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Message Center data" && git push)
